name: niclassifyenv
channels:
  - defaults
  - bioconda
  - auto
  - bfurneaux
  - conda-forge
dependencies:
  - python=3.9.0
  - pip
  - pip:
    - userpaths==0.*
    - python-nexus==2.*
    - PyInquirer
    - typer[all]==0.7.*
    # - -e niclassify/bin/PTP/master
  - biopython==1.*
  - pandas==1.*
  - dask==2022.*
  - pyqt==5.*
  - pyqt5-sip==12.*
  - requests==2.*
  - scikit-learn==1.*
  - seaborn==0.*
  - xlrd==2.*
  - natsort==7.*
  - ratelimiter==1.*
