[project]
name = "niclassify"
version = "2.0.0"
description = "A CLI toolkit for predictively classifying arthropod sequences as native/introduced"
authors = [
    { name = "Jackson Callaghan", email = "43009413+tokebe@users.noreply.github.com" },
]
requires-python = "~=3.11,<3.13"
readme = "README.md"
license = "GPL-3.0-only"
keywords = ["niclassify", "classification", "arthropod"]
dependencies = [
    "userpaths~=0.1",
    "python-nexus~=2.9",
    "biopython~=1.85",
    "scikit-learn~=1.6",
    "natsort~=7.1",
    "throttler~=1.2",
    "ratelimit~=2.2",
    "backoff~=2.2",
    "dotmap~=1.3",
    "httpx~=0.27",
    "bptp",
    "pyqt5~=5.15",
    "pyyaml~=6.0",
    "typer~=0.16",
    "pydantic~=2.11",
    "pydantic-settings~=2.10",
    "chardet~=5.2",
    "polars~=1.31",
    "inquirerpy>=0.3.4",
]

[project.urls]
Repository = "https://tokebe/niclassify"

[project.scripts]
niclassify = "niclassify.__main__:app"
nic = "niclassify.__main__:app"

[dependency-groups]
dev = [
    "jupyter>=1.0.0,<2",
    "ipython>=8.19.0,<9",
    "absolufy-imports>=0.3.1,<0.4",
    "taskipy>=1.14.1",
    "ruff>=0.12.2",
    "basedpyright>=1.29.5",
    "yamlfix>=1.17.0",
    "bpython>=0.25",
]

[tool.uv]
package = true
config-settings = { editable_mode = "compat" }

[tool.uv.sources]
bptp = { path = "src/niclassify/bin/bptp", editable = true }

[tool.taskipy.tasks]
lint = 'ruff check src/niclassify'
'lint:stats' = 'task lint --statistics'
'lint:watch' = 'task lint --watch'
'lint:fix' = 'task lint --fix'

typecheck = 'basedpyright src/niclassify'
'typecheck:watch' = 'task typecheck --watch'

format = 'ruff format --diff src/niclassify'
'format:fix' = 'ruff format src/niclassify'

fixup = """
echo 'Formatting...' &&
task format:fix &&
echo 'Linting...' &&
task lint:fix &&
echo 'Static analysis...' &&
task typecheck &&
echo "✅ All set!"
"""

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    # All of these were carefully chosen, see https://docs.astral.sh/ruff/rules
    # Pyflakes
    'F',
    # Pycodestyle errors, warning
    'E4',
    'E7',
    'E9',
    'W',
    # isort (sort imports)
    'I',
    # Pydocstyle (document your code!)
    'D',
    # Pep8 naming conventions (but slightly less pedantic)
    'N80',
    # Pyupgrade (use newer conventions)
    'UP',
    # Flake8-bugbear
    'B',
    # Flake8-annotations (require type annotations)
    'ANN0',
    'ANN2',
    # Flake8-builtins (don't overwrite builtins)
    'A',
    # Flake8-comprehensions
    'C4',
    # Flake8-logging-format
    'G',
    # Flake8-simplify
    'SIM',
    # Flake8-use-pathlib (pathlib is just better)
    'PTH',
    # Pylint
    'PL',
    # FastAPI
    'FAST',
    # Perflint
    'PERF',
    # Refurb
    'FURB',
    # Ruff-specific
    'RUF',
]
ignore = ['D100', 'D206', 'D300']

[tool.ruff.lint.pydocstyle]
convention = 'google'

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.format]
docstring-code-format = true

[tool.pyright]
# Make any allowable. Builtins sometimes deal in Any and aren't worth the extra modeling
reportAny = false
reportExplicitAny = false
reportUnusedCallResult = false # Just makes code look worse; Usually unused results are deliberately ignored
reportMissingTypeStubs = false # Sometimes type stubs aren't available and auto-gen is incorrect

[tool.yamlfix]
line_length = 88
