[project]
name = "niclassify"
version = "2.0.0"
description = "A CLI toolkit for predictively classifying arthropod sequences as native/introduced"
authors = [{ name = "Jackson Callaghan", email = "43009413+tokebe@users.noreply.github.com" }]
requires-python = "~=3.11"
readme = "README.md"
license = "GPL-3.0-only"
keywords = [
    "niclassify",
    "classification",
    "arthropod",
]
dependencies = [
    "userpaths==0.*",
    "python-nexus>=2.9.0,<3",
    "typer[all]==0.7.*",
    "biopython==1.*",
    "PyQt5-sip==12.*",
    "requests==2.*",
    "scikit-learn==1.*",
    "seaborn==0.*",
    "xlrd==2.*",
    "natsort==7.*",
    "throttler>=1.2.2,<2",
    "ratelimit>=2.2.1,<3",
    "backoff>=2.2.1,<3",
    "polars>=1.5.0,<2",
    "pydantic>=2.7.3,<3",
    "dotmap>=1.3.30,<2",
    "httpx>=0.27.0,<0.28",
    "bptp",
    "pyqt5>=5.15.11,<6",
    "bullet>=2.2.0,<3",
]

[project.urls]
Repository = "https://tokebe/niclassify"

[project.scripts]
niclassify = "niclassify.__main__:app"
nic = "niclassify.__main__:app"

[dependency-groups]
dev = [
    "jupyter>=1.0.0,<2",
    "ipython>=8.19.0,<9",
    "absolufy-imports>=0.3.1,<0.4",
]

[tool.uv]

[tool.uv.sources]
bptp = { path = "niclassify/bin/bptp", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
